Cargo.toml
docs/src/cli.md
docs/src/tutorials/first_app/setup.md
examples/basic/Cargo.toml
examples/cli/.perseus/Cargo.toml
examples/cli/.perseus/bonnie.toml
examples/cli/.perseus/server/Cargo.toml
examples/cli/.perseus/src/lib.rs
examples/cli/Cargo.toml
examples/i18n/Cargo.toml
examples/showcase/Cargo.toml
packages/perseus-actix-web/Cargo.toml
packages/perseus/Cargo.toml
packages/perseus/src/router.rs
packages/perseus/src/template.rs
packages/perseus/src/translator/mod.rs

Updates sycamore to 0.6.0, removes patch dependencies

Update Sycamore to v0.6.0

---

examples/basic/src/templates/index.rs
examples/i18n/tests/main.rs
packages/perseus-actix-web/src/initial_load.rs
packages/perseus-actix-web/src/page_data.rs
packages/perseus/src/default_headers.rs
packages/perseus/src/lib.rs
packages/perseus/src/locale_detector.rs
packages/perseus/src/template.rs

This allows a template to set HTTP headers for responses in which it's successfully returned, with an aim at allowing sensible and customizable cache control for revalidating pages.

Add HTTP header setting

---

packages/perseus-actix-web/src/initial_load.rs
packages/perseus-cli/src/bin/main.rs
packages/perseus-cli/src/build.rs
packages/perseus-cli/src/export.rs
packages/perseus-cli/src/parse.rs
packages/perseus-cli/src/serve.rs
packages/perseus/src/translations_manager.rs

This adds a new flag to the `build`, `serve`, and `export` commands in the CLI that will build for production, making it now possible to deploy Perseus apps in production (technically, it's still not recommended though).
Closes #30.

Add `--release` to CLI

---

docs/0.3.x/src/strategies/build-paths.md
docs/next/src/strategies/build-paths.md
examples/basic/.perseus/src/lib.rs
examples/i18n/src/templates/post.rs
packages/perseus/src/build.rs

This fixes the issue of build paths not being able to render root paths, and also adds documentation on achieving that goal. This should be released as v0.3.0-beta.2.

Fix build paths

---

docs/0.1.x/en-US/cli.md
docs/0.2.x/en-US/cli.md
docs/0.3.x/en-US/cli.md
docs/next/en-US/cli.md

Otherwise, it doesn't reload, since `perseus serve` is long-lived.

Add -r flag to entr commands in docs

---

docs/0.3.x/en-US/SUMMARY.md
docs/0.3.x/en-US/deploying/docker.md
docs/next/en-US/SUMMARY.md
docs/next/en-US/deploying/docker.md

`esbuild` and `wasm-opt` optimization steps aren't explained and also there isn't any css optimization `esbuild` step included as hello world examples don't yet contain any css file, but I think this is good enough for starters. Feel free to change anything, even any of the wording used, or suggest a change.

Add Docker deployment docs

---

bonnie.toml

Without the `npm i --prefix ./website` step prior to `bonnie site run` an error as bellow is thrown and styles on the website are all out of place.
```sh
(node:17003) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tailwindcss/defaultTheme'
Require stack:
- /home/user/perseus/website/tailwind.config.js
- /home/user/emsdk/node/14.15.5_64bit/lib/node_modules/tailwindcss/lib/cli.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/home/user/perseus/website/tailwind.config.js:1:22)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at …
```

Add website node modules install step to `bonnie setup`

---

examples/basic/.perseus/builder/src/bin/export_error_page.rs
packages/perseus-actix-web/src/configurer.rs
packages/perseus-actix-web/src/initial_load.rs
packages/perseus-warp/src/initial_load.rs
packages/perseus-warp/src/perseus_routes.rs
packages/perseus/src/export.rs
packages/perseus/src/html_shell.rs
packages/perseus/src/server/build_error_page.rs

I've added some tests to `html_shell.rs`. They don't really assert anything, but I used them to be able to quickly print out the output while refactoring to make sure that it looks right. I figured I'd leave them in for now in case you wanted to try running the code yourself while reviewing.
`window.__PERSEUS_RENDER_CFG` now gets defined at the top of `<head>` instead of bottom, but I don't think that should change much. You know the code better than me though, so I figured I'd mention it just in case.
I tried running the tests on my laptop, but they took a really long time since my specs aren't that great and I also ran into an issue with `geckodriver`. Maybe you could run the tests in CI?
Let me know if you think there's more room for improvement or something should be changed!
Closes …

Refactor html_shell.rs to improve readability

---

docs/next/en-US/SUMMARY.md
docs/next/en-US/templates/router-state.md
examples/basic/.perseus/src/lib.rs
examples/showcase/src/lib.rs
examples/showcase/src/templates/mod.rs
examples/showcase/src/templates/router_state.rs
packages/perseus/src/build.rs
packages/perseus/src/lib.rs
packages/perseus/src/plugins/plugins_list.rs
packages/perseus/src/router.rs
packages/perseus/src/server/render.rs
packages/perseus/src/shell.rs
packages/perseus/src/template.rs

This adds support for router state to Perseus, including a new example in `examples/showcase/` and documentation in the section on templates. It's likely that the router state provided will be extended in future, but, for now, it includes just one property about the router's load state, which can be used to create custom routing progress bars and the like.
Closes #106.

Add router state

---

docs/0.2.x/en-US/hello-world.md
docs/0.3.x/en-US/hello-world.md
docs/next/en-US/hello-world.md

Add missing link to WebAssembly website

---

packages/perseus/src/init.rs

Fixes a typo in the default index HTML and removes comment that is no longer valid.

fix: typo in default index view

---

examples/core/basic/.perseus/Cargo.toml
examples/core/basic/Cargo.toml
examples/core/freezing_and_thawing/Cargo.toml
examples/core/global_state/Cargo.toml
examples/core/i18n/Cargo.toml
examples/core/idb_freezing/Cargo.toml
examples/core/plugins/Cargo.toml
examples/core/router_state/Cargo.toml
examples/core/rx_state/Cargo.toml
examples/core/set_headers/Cargo.toml
examples/core/state_generation/Cargo.toml
examples/core/static_content/Cargo.toml
examples/core/unreactive/Cargo.toml
packages/perseus-actix-web/Cargo.toml
packages/perseus-macro/Cargo.toml
packages/perseus-warp/Cargo.toml
packages/perseus/Cargo.toml
packages/perseus/src/template/core.rs
packages/perseus/src/utils/context.rs

TODO: this currently uses a hack that I'm not so proud of. I'll probably need to release a new version of sycamore to do this properly but at least the problem is fixed.
The problem with hydration was that hydration keys were rendered in the head strings. This would cause a conflict when hydrating because there would be multiple nodes with the same hydration keys. That, in turn, is because there are multiple calls to `render_to_string`, each which creates a new "hydration context".
Note that this is a PR against the `feat-sycamore-0.4.0` branch instead of the `main` branch.

Fix hydration by not inserting hydration keys in `<head>`

---

packages/perseus-cli/src/deploy.rs

The current `deploy` commands for the CLI creates a pkg folder and copy the server binary with filename `server`, even on Windows. I still can change the binary name and add exe extension to it and it will run just fine.
This PR aims to fix the binary name for Windows to `server.exe`.

Fix `server` binary name in pkg. (Windows)

---

packages/perseus-actix-web/Cargo.toml

This PR aims to update the actix integration dependencies to the current stable release of actix-web.
Some other actix packages are also updated accordingly. I have checked that this build the default "Hello World" (with actix-web integration of course) example with no problem.
There is also another side project I'm working on which I also checked that works correctly with this updated version. Everything Just Works™.

Update to actix-web 4.1.0

---

examples/.base/src/main.rs

I didn't want to edit your in-depth explanation from the foldable pane, and without that, it would be kind of duplication, so instead, I opted to add a comment to the main.rs example. That way, if someone just copies the code, he'll have information right there, without the need to dig through the page.
I saw other integrations, so I added them, but maybe you don't want them exposed - let me know if you want some tweaking on this.

docs: add instruction to replace perseus_integration

---

Cargo.toml
examples/core/plugins/src/plugin.rs
examples/core/router_state/src/templates/index.rs
packages/perseus-macro/src/template.rs
packages/perseus/src/client.rs
packages/perseus/src/lib.rs
packages/perseus/src/router/get_initial_view.rs
packages/perseus/src/router/get_subsequent_view.rs
packages/perseus/src/router/mod.rs
packages/perseus/src/router/page_disposer.rs
packages/perseus/src/router/route_manager.rs
packages/perseus/src/router/router_component.rs
packages/perseus/src/template/core.rs

Right now, Perseus renders all user pages under the single, global `cx` scope, which is used for the entire app. This works well, until you use something like the router state (a global entity) and log every time there's a page change. I tried this in my rebuild of my own blog, and found very quickly that the logs were accumulating: the listeners were not being killed when I was navigating off the page. In other words, all listeners on global events were accumulating in Perseus apps. This may have been the cause of the error I occasionally observed while working on the Perseus website for long stretches, whereby my browser would freeze up after a few hours until I killed the tab. I now believe that *may* have been due to listener accumulations and improper memory clearing.
This PR adds a …

Use child scopes for pages

---

website/plugins/en-US/tailwind.json

This adds the Tailwind Plugin I wrote to the plugin directory. It downloads and initializes the Tailwind standalone CLI and then compiles the Tailwind CSS at build time. All platforms that have a binary available are supported (Linux x64/arm, macOS x64/arm, Windows x64).

Add Tailwind plugin to plugin directory

---

packages/perseus-cli/src/export.rs
packages/perseus-cli/src/install.rs

Fixes the cli bug for windows.
Also fixes a small typo in symlinking code inside export.rs.

Fix for #227

---

CONTRIBUTING.md

The current link ends up redirecting me to `https://framesurge.sh/perseus/en-US/tribble/workflowhttps:/framesurge.sh/perseus`, which is a 404.

fix: broken Tribble link

---

packages/perseus-cli/src/init.rs

hey :)
just a minimal change as a start as we will always wish to add the `target` folder to the `.gitignore`.

chore: added target to generated gitignore

---

packages/perseus/src/reactor/global_state.rs
packages/perseus/src/reactor/state.rs

This fixes #259
I could not run all tests, lots of building for a long time that ended abruptly with an unknown command `rust-script`. Hopefully the CI can  give a better feedback on this than I could.
Since HSR is a development feature (right?), I just "wrapped" the problematic if conditions inside the debug guard. Let me know if that was not the right solution.

Could not build a --release perseus app in beta.19

---

.gitignore
bonnie.toml

Changing `RUSTFLAGS` invalidates Cargo's cache. `bonnie check` and `bonnie test core` set `RUSTFLAGS`, so they would cause spurious rebuilds (particularly noticeable when using rust-analyzer).
Use separate target directories to get around this, similar to what perseus-cli does (and use its naming scheme, although `target_wasm` is not really correct...).
Tested by running `bonnie test`, then `bonnie check` and `bonnie test core`, making sure those last two do not cause rebuilds. This confirmed the separate `target_engine_clientdoc` is necessary: without it, alternating between `bonnie check` and `bonnie test core` rebuilds everything.

Use per-`RUSTFLAGS` Cargo target dirs in bonnie

---

examples/core/state_generation/Cargo.toml
examples/core/state_generation/src/templates/incremental_generation.rs
packages/perseus/src/errors.rs
packages/perseus/src/template/fn_types.rs

By generalizing the supported errors in state generation from types that directly implement `std::error::Error` to types that can be converted into a boxed `std::error::Error`, we can make `anyhow::Error` work.
I first tried to support just `anyhow::Error` specifically (in addition to the already-supported error types), but the compiler does not easily allow that: it thinks `anyhow::Error` might implement `std::error::Error` in the future, so it will not let me implement things on both. Please make sure the broader support for error types this adds is reasonable (and that I am correct about this change being backwards-compatible) before merging.

Support `anyhow::Error` in state generation functions

---

packages/perseus-cli/src/install.rs

CLi was still downloading for an intel chip it seemed, this fixes that.

fix aarch64 downloads for wasm-bindgen MacOS m2

---

packages/perseus-actix-web/src/lib.rs
packages/perseus-axum/src/lib.rs
packages/perseus-rocket/src/lib.rs
packages/perseus-warp/src/lib.rs
packages/perseus/src/errors.rs
packages/perseus/src/init.rs
packages/perseus/src/server/html_shell.rs
packages/perseus/src/state/global_state.rs
packages/perseus/src/template/widget_component.rs
packages/perseus/src/turbine/build.rs
packages/perseus/src/turbine/build_error_page.rs
packages/perseus/src/turbine/export.rs
packages/perseus/src/turbine/initial_consts.rs
packages/perseus/src/turbine/mod.rs
packages/perseus/src/turbine/server.rs

This PR removes the definitions of the render configuration and translations from the HTML bundle in initial loads, instead moving them to `/.perseus/initial_consts/<locale>.js`, with an unlocalized version at `/.perseus/initial_consts.js`. These are new routes that will need to be supported by all server integrations, but otherwise this is not a breaking change, and it purely alters implementation details.
The reason for this change is to change the page load scaling properties of Perseus: right now, very large apps with many pages have longer initial page loads, even for very simple pages, because Perseus injects a JSON sitemap (called the render configuration) into the HTML bundle so it knows how the routing of the app works. So, as the site gets bigger, so does every initial load …

Switch to JS for defining internal constants

---

docs/next/en-US/fundamentals/hydration.md

Fixing a typo in the documentation. Single word.

Fix a typo on hydration.md

---

docs/next/en-US/first-app/generating-pages.md

I was reading the book and I encountered a small typo, `e.g. fora blog`, which I corrected with my first PR for `perseus`. Thanks.

Small typo fix in docs/generating-pages.md

---

packages/perseus-cli/src/lib.rs

Like described inside this issue: [309](https://github.com/framesurge/perseus/issues/309) `perseus serve -w` is very slow when listening to a large number of files. 
This PR will not fix this in every case but it adds the `node_modules` folder to the watch exclusions. The 'node_modules' folder is similar to the `target` folder but from [npm](https://www.npmjs.com/) and it's often huge. I think a lot of developer has a `node_modules` folder because they are using [bootstrap](https://getbootstrap.com/), [tailwind](https://tailwindcss.com/) or some other npm dependencies inside there perseus projects.

feat(perseus-cli): add 'node_modules' to watch exclusions

---

docs/0.4.x/en-US/fundamentals/i18n.md

To clarify, the feature flag for internationalization must be added to `Cargo.toml` to enable the i18n feature.

docs: clarify the feature flag

---

.github/workflows/bench.yml
.github/workflows/ci.yml
.gitignore
.idea/.gitignore
examples/core/preload/Cargo.toml
packages/perseus-cli/Cargo.toml
packages/perseus-cli/src/deploy.rs
packages/perseus-cli/src/errors.rs

Please add the following cargo updates while I work on others.

few cargo updates
